-- Create Generic Medicines Table
CREATE TABLE IF NOT EXISTS generic_medicines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL COMMENT 'Medicine brand name',
    generic_name VARCHAR(255) NOT NULL COMMENT 'Generic/scientific name',
    manufacturer VARCHAR(255) COMMENT 'Manufacturing company',
    strength VARCHAR(100) COMMENT 'Medicine strength (e.g., 500mg, 10ml)',
    dosage_form VARCHAR(100) COMMENT 'Form (tablet, capsule, syrup, injection)',
    price DECIMAL(10,2) DEFAULT 0.00 COMMENT 'Price in BDT',
    description TEXT COMMENT 'Additional description',
    is_active BOOLEAN DEFAULT TRUE COMMENT 'Active status',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes for better search performance
    INDEX idx_name (name),
    INDEX idx_generic_name (generic_name),
    INDEX idx_manufacturer (manufacturer),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    
    -- Full text search index for better search functionality
    FULLTEXT KEY ft_search (name, generic_name, manufacturer, strength, dosage_form)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Generic Medicines Master Table';

-- Insert 50 common Indian medicines
INSERT INTO generic_medicines (name, generic_name, manufacturer, strength, dosage_form, price, description) VALUES
('Crocin', 'Paracetamol', 'GSK', '500mg', 'Tablet', 15.00, 'Pain reliever and fever reducer'),
('Dolo 650', 'Paracetamol', 'Micro Labs', '650mg', 'Tablet', 18.50, 'Fever and pain relief'),
('Combiflam', 'Ibuprofen + Paracetamol', 'Sanofi', '400mg+325mg', 'Tablet', 25.00, 'Pain and inflammation relief'),
('Disprin', 'Aspirin', 'Reckitt Benckiser', '325mg', 'Tablet', 12.00, 'Pain reliever and blood thinner'),
('Voveran', 'Diclofenac', 'Novartis', '50mg', 'Tablet', 22.00, 'Anti-inflammatory drug'),
('Pantop', 'Pantoprazole', 'Aristo Pharma', '40mg', 'Tablet', 35.00, 'Acid reducer'),
('Omez', 'Omeprazole', 'Dr. Reddys', '20mg', 'Capsule', 28.00, 'Proton pump inhibitor'),
('Ranitidine', 'Ranitidine', 'GSK', '150mg', 'Tablet', 20.00, 'Acid reducer'),
('Cetirizine', 'Cetirizine', 'Cipla', '10mg', 'Tablet', 15.00, 'Antihistamine for allergies'),
('Allegra', 'Fexofenadine', 'Sanofi', '120mg', 'Tablet', 45.00, 'Allergy medication'),
('Azithral', 'Azithromycin', 'Alembic Pharma', '500mg', 'Tablet', 85.00, 'Antibiotic'),
('Augmentin', 'Amoxicillin + Clavulanate', 'GSK', '625mg', 'Tablet', 120.00, 'Antibiotic combination'),
('Ciprofloxacin', 'Ciprofloxacin', 'Ranbaxy', '500mg', 'Tablet', 65.00, 'Broad spectrum antibiotic'),
('Norflox', 'Norfloxacin', 'Cipla', '400mg', 'Tablet', 55.00, 'Antibiotic for UTI'),
('Metrogyl', 'Metronidazole', 'J&J', '400mg', 'Tablet', 30.00, 'Antibiotic and antiprotozoal'),
('Amlodipine', 'Amlodipine', 'Pfizer', '5mg', 'Tablet', 25.00, 'Blood pressure medication'),
('Telmisartan', 'Telmisartan', 'Boehringer', '40mg', 'Tablet', 45.00, 'Hypertension treatment'),
('Atenolol', 'Atenolol', 'Cipla', '50mg', 'Tablet', 18.00, 'Beta blocker for BP'),
('Metformin', 'Metformin', 'USV', '500mg', 'Tablet', 12.00, 'Diabetes medication'),
('Glimepiride', 'Glimepiride', 'Sanofi', '2mg', 'Tablet', 35.00, 'Diabetes treatment'),
('Insulin', 'Human Insulin', 'Novo Nordisk', '100IU/ml', 'Injection', 450.00, 'Diabetes insulin therapy'),
('Atorvastatin', 'Atorvastatin', 'Pfizer', '20mg', 'Tablet', 85.00, 'Cholesterol medication'),
('Rosuvastatin', 'Rosuvastatin', 'AstraZeneca', '10mg', 'Tablet', 95.00, 'Statin for cholesterol'),
('Clopidogrel', 'Clopidogrel', 'Sanofi', '75mg', 'Tablet', 125.00, 'Blood thinner'),
('Ecosprin', 'Aspirin', 'USV', '75mg', 'Tablet', 8.00, 'Low dose aspirin'),
('Levothyroxine', 'Levothyroxine', 'Abbott', '50mcg', 'Tablet', 45.00, 'Thyroid hormone'),
('Prednisolone', 'Prednisolone', 'Wyeth', '10mg', 'Tablet', 25.00, 'Corticosteroid'),
('Betamethasone', 'Betamethasone', 'GSK', '0.5mg', 'Tablet', 35.00, 'Anti-inflammatory steroid'),
('Montelukast', 'Montelukast', 'Merck', '10mg', 'Tablet', 85.00, 'Asthma medication'),
('Salbutamol', 'Salbutamol', 'Cipla', '4mg', 'Tablet', 15.00, 'Bronchodilator'),
('Deriphyllin', 'Theophylline', 'Zydus Cadila', '300mg', 'Tablet', 45.00, 'Asthma treatment'),
('Domperidone', 'Domperidone', 'Cipla', '10mg', 'Tablet', 18.00, 'Anti-nausea medication'),
('Ondansetron', 'Ondansetron', 'GSK', '4mg', 'Tablet', 55.00, 'Anti-vomiting drug'),
('Loperamide', 'Loperamide', 'J&J', '2mg', 'Tablet', 25.00, 'Anti-diarrheal'),
('ORS', 'Oral Rehydration Salt', 'WHO Formula', '21g', 'Powder', 8.00, 'Dehydration treatment'),
('Paracetamol Syrup', 'Paracetamol', 'Cipla', '120mg/5ml', 'Syrup', 35.00, 'Pediatric fever reducer'),
('Iron Tablets', 'Ferrous Sulfate', 'Ranbaxy', '200mg', 'Tablet', 15.00, 'Iron deficiency treatment'),
('Calcium', 'Calcium Carbonate', 'Cipla', '500mg', 'Tablet', 25.00, 'Calcium supplement'),
('Vitamin D3', 'Cholecalciferol', 'Sun Pharma', '60000IU', 'Capsule', 45.00, 'Vitamin D supplement'),
('B-Complex', 'Vitamin B Complex', 'Pfizer', 'Multi', 'Tablet', 35.00, 'B vitamin supplement'),
('Multivitamin', 'Multivitamin', 'Centrum', 'Multi', 'Tablet', 85.00, 'Complete vitamin supplement'),
('Diazepam', 'Diazepam', 'Ranbaxy', '5mg', 'Tablet', 12.00, 'Anti-anxiety medication'),
('Alprazolam', 'Alprazolam', 'Pfizer', '0.5mg', 'Tablet', 25.00, 'Anxiety treatment'),
('Fluoxetine', 'Fluoxetine', 'Eli Lilly', '20mg', 'Capsule', 85.00, 'Antidepressant'),
('Amitriptyline', 'Amitriptyline', 'Sun Pharma', '25mg', 'Tablet', 18.00, 'Tricyclic antidepressant'),
('Gabapentin', 'Gabapentin', 'Pfizer', '300mg', 'Capsule', 125.00, 'Nerve pain medication'),
('Tramadol', 'Tramadol', 'Cipla', '50mg', 'Tablet', 45.00, 'Pain reliever'),
('Ketoconazole', 'Ketoconazole', 'J&J', '200mg', 'Tablet', 65.00, 'Antifungal medication'),
('Fluconazole', 'Fluconazole', 'Pfizer', '150mg', 'Tablet', 85.00, 'Antifungal treatment'),
('Acyclovir', 'Acyclovir', 'GSK', '400mg', 'Tablet', 125.00, 'Antiviral medication');