CREATE TABLE IF NOT EXISTS appointment_booking_app_rozerpaysecrect (
  id INT AUTO_INCREMENT PRIMARY KEY,
  razorpay_key VARCHAR(255) NOT NULL,
  razorpay_secret VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);